export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const CHANGE_LOGIN_LOGOUT = "CHANGE_LOGIN_LOGOUT";


export const GET_USER_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_FAILURE = "GET_COLLEGE_DATA_FAILURE";